In [2]:
#Q1: Load the Titanic dataset (or any CSV with missing values) and count missing values in each column using isnull().sum()

import pandas as pd
import numpy as np

data = pd.read_csv(r"C:\Users\Dell\OneDrive\Desktop\Data Analyst 2.0\Python Projects\Day 12\employee_dirty_dataset_1000_rows.csv")

In [3]:
data

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate
0,1,Employee_1,58.0,Male,Finance,49256.0,Pune,2023-01-31
1,2,Employee_2,32.0,Female,Finance,91426.0,Aurangabad,2023-10-12
2,3,Employee_3,28.0,Male,Sales,48221.0,Nagpur,2023-04-10
3,4,Employee_4,20.0,Male,IT,90284.0,Kolhapur,2024-09-25
4,5,Employee_5,41.0,Female,Sales,106673.0,Nagpur,2023-10-12
...,...,...,...,...,...,...,...,...
995,5,Employee_5,41.0,Female,Sales,106673.0,Nagpur,2023-10-12
996,4,Employee_4,20.0,Male,IT,90284.0,Kolhapur,2024-09-25
997,3,Employee_3,28.0,Male,Sales,48221.0,Nagpur,2023-04-10
998,2,Employee_2,32.0,Female,Finance,91426.0,Aurangabad,2023-10-12
999,1,Employee_1,58.0,Male,Finance,49256.0,Pune,2023-01-31

In [4]:
data.isnull().sum()

EmployeeID      0
Name            0
Age            36
Gender          0
Department    178
Salary         30
City            0
JoinDate        0
dtype: int64

In [5]:
#Q2: Drop rows that contain any missing values using dropna().

dropna_data = data.dropna()

dropna_data

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate
0,1,Employee_1,58.0,Male,Finance,49256.0,Pune,2023-01-31
1,2,Employee_2,32.0,Female,Finance,91426.0,Aurangabad,2023-10-12
2,3,Employee_3,28.0,Male,Sales,48221.0,Nagpur,2023-04-10
3,4,Employee_4,20.0,Male,IT,90284.0,Kolhapur,2024-09-25
4,5,Employee_5,41.0,Female,Sales,106673.0,Nagpur,2023-10-12
...,...,...,...,...,...,...,...,...
995,5,Employee_5,41.0,Female,Sales,106673.0,Nagpur,2023-10-12
996,4,Employee_4,20.0,Male,IT,90284.0,Kolhapur,2024-09-25
997,3,Employee_3,28.0,Male,Sales,48221.0,Nagpur,2023-04-10
998,2,Employee_2,32.0,Female,Finance,91426.0,Aurangabad,2023-10-12
999,1,Employee_1,58.0,Male,Finance,49256.0,Pune,2023-01-31

In [6]:
dropna_data.isnull().sum()

EmployeeID    0
Name          0
Age           0
Gender        0
Department    0
Salary        0
City          0
JoinDate      0
dtype: int64

In [7]:
#Q3: Fill missing numeric values with the column mean using fillna().

data.head(50)

data = data.fillna(data.mean(numeric_only=True))

data.tail(50)

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate
950,951,Employee_951,48.0,female,HR,117055.0,Aurangabad,2023-05-28
951,952,Employee_952,49.0,FEMALE,Marketing,59438.0,Kolhapur,2023-07-25
952,953,Employee_953,18.0,Male,Finance,52401.0,Nagpur,2023-02-26
953,954,Employee_954,37.0,female,Marketing,100315.0,Pune,2024-03-18
954,955,Employee_955,19.0,FEMALE,Finance,42383.0,Nashik,2023-10-24
955,956,Employee_956,60.0,FEMALE,Finance,34068.0,Mumbai,2023-01-29
956,957,Employee_957,18.0,Male,IT,106139.0,Mumbai,2024-04-24
957,958,Employee_958,28.0,male,NaN,85619.0,Aurangabad,2024-02-04
958,959,Employee_959,40.0,female,IT,38355.0,Nagpur,2023-03-11
959,960,Employee_960,59.0,Female,NaN,86450.0,Nashik,2024-08-25
960,961,Employee_961,40.0,Female,Sales,25888.0,Kolhapur,2023-04-19
961,962,Employee_962,48.0,FEMALE,Sales,42806.0,Pune,2024-09-18
962,963,Employee_963,22.0,male,Sales,69063.0,Kolhapur,2024-04-05
963,964,Employee_964,58.0,Female,HR,108978.0,Kolhapur,2023-06-15
964,965,Employee_965,51.0,Female,Sales,96298.0,Mumbai,2023-01-06
965,966,Employee_966,22.0,Female,HR,115457.0,Aurangabad,2025-04-27
966,967,Employee_967,40.0,Male,Marketing,101981.0,Pune,2023-05-11
967,968,Employee_968,37.0,Female,IT,26747.0,Nashik,2024-02-04
968,969,Employee_969,28.0,FEMALE,Marketing,51640.0,Pune,2024-07-13
969,970,Employee_970,25.0,male,Sales,24230.0,Mumbai,2023-07-29
970,971,Employee_971,39.0,male,Sales,50882.0,Nagpur,2024-09-04
971,972,Employee_972,23.0,FEMALE,Marketing,55456.0,Mumbai,2024-10-27
972,973,Employee_973,48.0,Male,Marketing,27255.0,Nagpur,2024-11-29
973,974,Employee_974,21.0,Male,HR,76324.0,Pune,2024-03-24
974,975,Employee_975,41.0,Female,Sales,45381.0,Aurangabad,2023-01-11
975,976,Employee_976,52.0,Female,IT,36608.0,Pune,2023-11-18
976,977,Employee_977,59.0,female,Sales,99445.0,Pune,2023-09-14
977,978,Employee_978,31.0,female,HR,68094.0,Aurangabad,2023-10-01
978,979,Employee_979,21.0,male,Sales,101509.0,Mumbai,2023-05-21
979,980,Employee_980,51.0,Female,NaN,36088.0,Nagpur,2024-10-27
980,20,Employee_20,53.0,FEMALE,Finance,32224.0,Nagpur,2023-08-07
981,19,Employee_19,30.0,Female,Sales,56509.0,Nagpur,2025-04-07
982,18,Employee_18,45.0,Male,Finance,81213.0,Kolhapur,2023-12-14
983,17,Employee_17,60.0,Female,Finance,114811.0,Nagpur,2023-07-14
984,16,Employee_16,22.0,Female,Sales,97128.0,Pune,2025-05-30
985,15,Employee_15,56.0,FEMALE,Marketing,108039.0,Nagpur,2023-05-04
986,14,Employee_14,23.0,female,Finance,119693.0,Aurangabad,2023-06-19
987,13,Employee_13,56.0,male,HR,71110.6,Pune,2023-09-04
988,12,Employee_12,34.0,Female,IT,101959.0,Mumbai,2024-07-06
989,11,Employee_11,25.0,Female,Finance,58469.0,Pune,2025-01-09
990,10,Employee_10,28.0,Male,Finance,71110.6,Aurangabad,2023-09-15
991,9,Employee_9,55.0,Male,Finance,96484.0,Pune,2025-02-12
992,8,Employee_8,54.0,Female,IT,104259.0,Mumbai,2023-09-10
993,7,Employee_7,28.0,Male,IT,109733.0,Nagpur,2023-10-02
994,6,Employee_6,41.0,Male,NaN,107841.0,Mumbai,2024-06-30
995,5,Employee_5,41.0,Female,Sales,106673.0,Nagpur,2023-10-12
996,4,Employee_4,20.0,Male,IT,90284.0,Kolhapur,2024-09-25
997,3,Employee_3,28.0,Male,Sales,48221.0,Nagpur,2023-04-10
998,2,Employee_2,32.0,Female,Finance,91426.0,Aurangabad,2023-10-12
999,1,Employee_1,58.0,Male,Finance,49256.0,Pune,2023-01-31

In [8]:
#Q4: Fill missing categorical values with the most frequent value (mode).

data = data.fillna(data.mode(numeric_only=True))

data

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate
0,1,Employee_1,58.0,Male,Finance,49256.0,Pune,2023-01-31
1,2,Employee_2,32.0,Female,Finance,91426.0,Aurangabad,2023-10-12
2,3,Employee_3,28.0,Male,Sales,48221.0,Nagpur,2023-04-10
3,4,Employee_4,20.0,Male,IT,90284.0,Kolhapur,2024-09-25
4,5,Employee_5,41.0,Female,Sales,106673.0,Nagpur,2023-10-12
...,...,...,...,...,...,...,...,...
995,5,Employee_5,41.0,Female,Sales,106673.0,Nagpur,2023-10-12
996,4,Employee_4,20.0,Male,IT,90284.0,Kolhapur,2024-09-25
997,3,Employee_3,28.0,Male,Sales,48221.0,Nagpur,2023-04-10
998,2,Employee_2,32.0,Female,Finance,91426.0,Aurangabad,2023-10-12
999,1,Employee_1,58.0,Male,Finance,49256.0,Pune,2023-01-31

In [9]:
#Q5: Detect and remove duplicate rows from a DataFrame using duplicated() and drop_duplicates().

data.duplicated()

data.duplicated().sum()

data = data.drop_duplicates()

In [10]:
data.duplicated().sum()

np.int64(0)

In [11]:
data.shape

(981, 8)

In [12]:
#Q6: Convert a column's data type (e.g., string to numeric) using astype() or pd.to_numeric()

data.dtypes

EmployeeID      int64
Name           object
Age           float64
Gender         object
Department     object
Salary        float64
City           object
JoinDate       object
dtype: object

In [13]:
data["Age"] = data["Age"].fillna(data["Age"].mean()).astype(int)

data.dtypes

C:\Users\Dell\AppData\Local\Temp\ipykernel_19300\2810272029.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Age"] = data["Age"].fillna(data["Age"].mean()).astype(int)

EmployeeID      int64
Name           object
Age             int64
Gender         object
Department     object
Salary        float64
City           object
JoinDate       object
dtype: object

In [14]:
data["JoinDate"] = pd.to_datetime(data["JoinDate"],errors = "coerce")

C:\Users\Dell\AppData\Local\Temp\ipykernel_19300\1225701390.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["JoinDate"] = pd.to_datetime(data["JoinDate"],errors = "coerce")

In [15]:
data.dtypes

EmployeeID             int64
Name                  object
Age                    int64
Gender                object
Department            object
Salary               float64
City                  object
JoinDate      datetime64[ns]
dtype: object

In [16]:
#Q8: Standardize inconsistent text data in a column (e.g., 'male', 'Male', 'MALE' -> 'Male').

#str.strip() → Removes extra spaces.
#str.capitalize() → Converts the first letter to uppercase and the rest to lowercase.

data["Gender"] = data["Gender"].str.strip().str.capitalize()

data

C:\Users\Dell\AppData\Local\Temp\ipykernel_19300\588740251.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Gender"] = data["Gender"].str.strip().str.capitalize()

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate
0,1,Employee_1,58,Male,Finance,49256.0,Pune,2023-01-31
1,2,Employee_2,32,Female,Finance,91426.0,Aurangabad,2023-10-12
2,3,Employee_3,28,Male,Sales,48221.0,Nagpur,2023-04-10
3,4,Employee_4,20,Male,IT,90284.0,Kolhapur,2024-09-25
4,5,Employee_5,41,Female,Sales,106673.0,Nagpur,2023-10-12
...,...,...,...,...,...,...,...,...
976,977,Employee_977,59,Female,Sales,99445.0,Pune,2023-09-14
977,978,Employee_978,31,Female,HR,68094.0,Aurangabad,2023-10-01
978,979,Employee_979,21,Male,Sales,101509.0,Mumbai,2023-05-21
979,980,Employee_980,51,Female,NaN,36088.0,Nagpur,2024-10-27
994,6,Employee_6,41,Male,NaN,107841.0,Mumbai,2024-06-30

In [17]:
#Q10: Replace specific values in a column using replace() (e.g., replace 'NaN' strings with actual NaN).

data["Department"] = data["Department"].replace(np.nan,"Unknown")

data

C:\Users\Dell\AppData\Local\Temp\ipykernel_19300\426398817.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Department"] = data["Department"].replace(np.nan,"Unknown")

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate
0,1,Employee_1,58,Male,Finance,49256.0,Pune,2023-01-31
1,2,Employee_2,32,Female,Finance,91426.0,Aurangabad,2023-10-12
2,3,Employee_3,28,Male,Sales,48221.0,Nagpur,2023-04-10
3,4,Employee_4,20,Male,IT,90284.0,Kolhapur,2024-09-25
4,5,Employee_5,41,Female,Sales,106673.0,Nagpur,2023-10-12
...,...,...,...,...,...,...,...,...
976,977,Employee_977,59,Female,Sales,99445.0,Pune,2023-09-14
977,978,Employee_978,31,Female,HR,68094.0,Aurangabad,2023-10-01
978,979,Employee_979,21,Male,Sales,101509.0,Mumbai,2023-05-21
979,980,Employee_980,51,Female,Unknown,36088.0,Nagpur,2024-10-27
994,6,Employee_6,41,Male,Unknown,107841.0,Mumbai,2024-06-30

In [18]:
#Q11: Create a new column that flags rows with missing values (1 if any missing, else 0)

data["Missing_flag"] = data.isnull().any(axis=1).astype(int)

C:\Users\Dell\AppData\Local\Temp\ipykernel_19300\3940009466.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Missing_flag"] = data.isnull().any(axis=1).astype(int)

In [19]:
data

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate,Missing_flag
0,1,Employee_1,58,Male,Finance,49256.0,Pune,2023-01-31,0
1,2,Employee_2,32,Female,Finance,91426.0,Aurangabad,2023-10-12,0
2,3,Employee_3,28,Male,Sales,48221.0,Nagpur,2023-04-10,0
3,4,Employee_4,20,Male,IT,90284.0,Kolhapur,2024-09-25,0
4,5,Employee_5,41,Female,Sales,106673.0,Nagpur,2023-10-12,0
...,...,...,...,...,...,...,...,...,...
976,977,Employee_977,59,Female,Sales,99445.0,Pune,2023-09-14,0
977,978,Employee_978,31,Female,HR,68094.0,Aurangabad,2023-10-01,0
978,979,Employee_979,21,Male,Sales,101509.0,Mumbai,2023-05-21,0
979,980,Employee_980,51,Female,Unknown,36088.0,Nagpur,2024-10-27,0
994,6,Employee_6,41,Male,Unknown,107841.0,Mumbai,2024-06-30,0

In [20]:
#Q13: Bin a continuous numeric column into categories using pd.cut() (e.g., Age into child/adult/senior).

data["Age_Group"] = pd.cut(data["Age"],bins=[0,18,40,60],labels = ["Child","Adult","Senior"])

C:\Users\Dell\AppData\Local\Temp\ipykernel_19300\1605567710.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Age_Group"] = pd.cut(data["Age"],bins=[0,18,40,60],labels = ["Child","Adult","Senior"])

In [21]:
print(data[["Age","Age_Group"]])

     Age Age_Group
0     58    Senior
1     32     Adult
2     28     Adult
3     20     Adult
4     41    Senior
..   ...       ...
976   59    Senior
977   31     Adult
978   21     Adult
979   51    Senior
994   41    Senior

[981 rows x 2 columns]

In [23]:
data["JoinDate"] = data["JoinDate"].fillna("2023-01-01")

C:\Users\Dell\AppData\Local\Temp\ipykernel_19300\1122543245.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["JoinDate"] = data["JoinDate"].fillna("2023-01-01")

In [24]:
#Q15: Combine all the above techniques to fully clean a raw dataset and export the cleaned version to a new CSV.

data.to_csv("Employee_Cleaned_dataset",index=False)

print("Cleaned Dataset Exported Successfully")

Cleaned Dataset Exported Successfully