In [2]:
import pandas as pd

#Q1: Create two small DataFrames (Employees and Departments) and merge them using pd.merge() on a common key.

Employees = pd.DataFrame({
    "EMP_ID":[1,2,3,4],
    "Name":["Rohit","Vaishnavi","Ganesh","Vaibhav"],
    "Dept_ID":[101,102,103,101]
})

Departments = pd.DataFrame({
    "Dept_ID":[101,102,103],
    "Department":["HR","Sales","Marketing"]
})

merged = pd.merge(Employees,Departments,on="Dept_ID")

merged

   EMP_ID       Name  Dept_ID Department
0       1      Rohit      101         HR
1       2  Vaishnavi      102      Sales
2       3     Ganesh      103  Marketing
3       4    Vaibhav      101         HR

In [3]:
#Q2: Perform an inner join, left join, right join, and outer join between two DataFrames, and explain the difference in results.


# Employees DataFrame
employees = pd.DataFrame({
    'Emp_ID': [101, 102, 103, 104],
    'Name': ['Rohit', 'Amit', 'Priya', 'Sneha'],
    'Dept_ID': [1, 2, 3, 4]
})

# Departments DataFrame
departments = pd.DataFrame({
    'Dept_ID': [1, 2, 3, 5],
    'Department': ['HR', 'IT', 'Finance', 'Marketing']
})

employees

   Emp_ID   Name  Dept_ID
0     101  Rohit        1
1     102   Amit        2
2     103  Priya        3
3     104  Sneha        4

In [4]:
departments

   Dept_ID Department
0        1         HR
1        2         IT
2        3    Finance
3        5  Marketing

In [5]:
# Inner Join

inner_join = pd.merge(employees,departments,on="Dept_ID",how="inner")

inner_join

   Emp_ID   Name  Dept_ID Department
0     101  Rohit        1         HR
1     102   Amit        2         IT
2     103  Priya        3    Finance

In [6]:
# Left Join

left_join = pd.merge(employees,departments,on="Dept_ID",how="left")

left_join

   Emp_ID   Name  Dept_ID Department
0     101  Rohit        1         HR
1     102   Amit        2         IT
2     103  Priya        3    Finance
3     104  Sneha        4        NaN

In [7]:
right_join = pd.merge(employees,departments,on="Dept_ID",how="right")

right_join

   Emp_ID   Name  Dept_ID Department
0   101.0  Rohit        1         HR
1   102.0   Amit        2         IT
2   103.0  Priya        3    Finance
3     NaN    NaN        5  Marketing

In [8]:
outer_join = pd.merge(employees,departments,on="Dept_ID",how = "outer")

outer_join

   Emp_ID   Name  Dept_ID Department
0   101.0  Rohit        1         HR
1   102.0   Amit        2         IT
2   103.0  Priya        3    Finance
3   104.0  Sneha        4        NaN
4     NaN    NaN        5  Marketing

In [9]:
#Q3: Concatenate two DataFrames with the same columns vertically using pd.concat().

# First DataFrame
df1 = pd.DataFrame({
    'Emp_ID': [101, 102],
    'Name': ['Rohit', 'Amit'],
    'Department': ['HR', 'IT']
})

# Second DataFrame
df2 = pd.DataFrame({
    'Emp_ID': [103, 104],
    'Name': ['Priya', 'Sneha'],
    'Department': ['Finance', 'Marketing']
})

result = pd.concat([df1,df2])

result

   Emp_ID   Name Department
0     101  Rohit         HR
1     102   Amit         IT
0     103  Priya    Finance
1     104  Sneha  Marketing

In [10]:
#Q4: Concatenate two DataFrames side by side (horizontally) using pd.concat(axis=1).

# First DataFrame
df1 = pd.DataFrame({
    'Emp_ID': [101, 102],
    'Name': ['Rohit', 'Amit'],
    'Department': ['HR', 'IT']
})

# Second DataFrame
df2 = pd.DataFrame({
    'Emp_ID': [103, 104],
    'Name': ['Priya', 'Sneha'],
    'Department': ['Finance', 'Marketing']
})

result =  pd.concat([df1,df2],axis = 1)

result

   Emp_ID   Name Department  Emp_ID   Name Department
0     101  Rohit         HR     103  Priya    Finance
1     102   Amit         IT     104  Sneha  Marketing

In [11]:
#Q5: Use join() to combine two DataFrames based on their index.

# First DataFrame
employees = pd.DataFrame({
    'Name': ['Rohit', 'Amit', 'Priya'],
    'Department': ['HR', 'IT', 'Finance']
}, index=[101, 102, 103])

# Second DataFrame
salary = pd.DataFrame({
    'Salary': [40000, 50000, 45000]
}, index=[101, 102, 103])


result = employees.join(salary)

result

      Name Department  Salary
101  Rohit         HR   40000
102   Amit         IT   50000
103  Priya    Finance   45000

In [12]:
#Q6: Merge two DataFrames on multiple key columns (e.g., Region and Year).

# Sales DataFrame
sales = pd.DataFrame({
    'Region': ['North', 'South', 'East', 'West'],
    'Year': [2023, 2023, 2024, 2024],
    'Sales': [50000, 60000, 55000, 70000]
})

# Profit DataFrame
profit = pd.DataFrame({
    'Region': ['North', 'South', 'East', 'Central'],
    'Year': [2023, 2023, 2024, 2024],
    'Profit': [10000, 12000, 11000, 9000]
})

result = pd.merge(sales,profit,on=["Region","Year"],how='outer')

result

    Region  Year    Sales   Profit
0  Central  2024      NaN   9000.0
1     East  2024  55000.0  11000.0
2    North  2023  50000.0  10000.0
3    South  2023  60000.0  12000.0
4     West  2024  70000.0      NaN

In [13]:
#Q7: Handle overlapping column names during a merge using the suffixes parameter.

employees = pd.DataFrame({
    'Emp_ID': [101, 102, 103],
    'Name': ['Rohit', 'Amit', 'Priya'],
    'Salary': [40000, 50000, 45000]
})

# Second DataFrame
bonus = pd.DataFrame({
    'Emp_ID': [101, 102, 103],
    'Salary': [5000, 6000, 5500],   # Overlapping column name
    'Bonus': [2000, 2500, 2200]
})

result = pd.merge(employees,bonus,on="Emp_ID",suffixes=["_employee","_bonus"])

result

   Emp_ID   Name  Salary_employee  Salary_bonus  Bonus
0     101  Rohit            40000          5000   2000
1     102   Amit            50000          6000   2500
2     103  Priya            45000          5500   2200

In [14]:
#Q9: Identify rows that exist in one DataFrame but not the other using an outer join with an indicator column.

# First DataFrame
employees = pd.DataFrame({
    'Emp_ID': [101, 102, 103, 104],
    'Name': ['Rohit', 'Amit', 'Priya', 'Sneha']
})

# Second DataFrame
new_employees = pd.DataFrame({
    'Emp_ID': [103, 104, 105, 106],
    'Name': ['Priya', 'Sneha', 'Rahul', 'Neha']
})

result = pd.merge(employees,new_employees,on=["Emp_ID","Name"],how="outer",indicator="True")

result

   Emp_ID   Name        True
0     101  Rohit   left_only
1     102   Amit   left_only
2     103  Priya        both
3     104  Sneha        both
4     105  Rahul  right_only
5     106   Neha  right_only

In [15]:
#Q10: Combine three or more DataFrames from different sources into a single master DataFrame.

# DataFrame 1: Employee Details
employees = pd.DataFrame({
    'Emp_ID': [101, 102, 103],
    'Name': ['Rohit', 'Amit', 'Priya']
})

# DataFrame 2: Department Details
departments = pd.DataFrame({
    'Emp_ID': [101, 102, 103],
    'Department': ['HR', 'IT', 'Finance']
})

# DataFrame 3: Salary Details
salary = pd.DataFrame({
    'Emp_ID': [101, 102, 103],
    'Salary': [40000, 50000, 45000]
})

result = pd.merge(employees,departments,on="Emp_ID")
result = pd.merge(result,salary,on="Emp_ID")

result

   Emp_ID   Name Department  Salary
0     101  Rohit         HR   40000
1     102   Amit         IT   50000
2     103  Priya    Finance   45000

In [16]:
#Q11: Merge a small lookup table (e.g., product ID to product name) into a larger sales DataFrame.

# Large Sales DataFrame
sales = pd.DataFrame({
    'Sale_ID': [1001, 1002, 1003, 1004, 1005],
    'Product_ID': [101, 102, 103, 101, 104],
    'Quantity': [2, 1, 5, 3, 4],
    'Amount': [1000, 1500, 2500, 1500, 4000]
})

# Small Lookup Table
products = pd.DataFrame({
    'Product_ID': [101, 102, 103, 104],
    'Product_Name': ['Laptop', 'Mouse', 'Keyboard', 'Monitor']
})

# Merge the lookup table into the sales DataFrame
master_sales = pd.merge(sales, products, on='Product_ID', how='left')

master_sales

   Sale_ID  Product_ID  Quantity  Amount Product_Name
0     1001         101         2    1000       Laptop
1     1002         102         1    1500        Mouse
2     1003         103         5    2500     Keyboard
3     1004         101         3    1500       Laptop
4     1005         104         4    4000      Monitor

In [17]:
#Q12: Use merge_ordered() or merge_asof() to combine time-series data from two sources.

# Sales DataFrame
sales = pd.DataFrame({
    'Date': ['2024-01-01', '2024-01-03', '2024-01-05'],
    'Sales': [1000, 1500, 1200]
})

# Expenses DataFrame
expenses = pd.DataFrame({
    'Date': ['2024-01-02', '2024-01-03', '2024-01-06'],
    'Expense': [500, 700, 400]
})

sales["Date"] = pd.to_datetime(sales['Date'])
expenses["Date"] = pd.to_datetime(expenses['Date'])

sales.dtypes

expenses.dtypes

result = pd.merge_ordered(sales,expenses,on="Date")

result

        Date   Sales  Expense
0 2024-01-01  1000.0      NaN
1 2024-01-02     NaN    500.0
2 2024-01-03  1500.0    700.0
3 2024-01-05  1200.0      NaN
4 2024-01-06     NaN    400.0

In [18]:
#Q13: After merging, handle any resulting missing values appropriately.

# Employee DataFrame
employees = pd.DataFrame({
    'Emp_ID': [101, 102, 103, 104],
    'Name': ['Rohit', 'Amit', 'Priya', 'Sneha'],
    'Dept_ID': [1, 2, 3, 4]
})

# Department DataFrame
departments = pd.DataFrame({
    'Dept_ID': [1, 2, 3],
    'Department': ['HR', 'IT', 'Finance']
})

result = pd.merge(employees,departments,on="Dept_ID",how="left")

result

   Emp_ID   Name  Dept_ID Department
0     101  Rohit        1         HR
1     102   Amit        2         IT
2     103  Priya        3    Finance
3     104  Sneha        4        NaN

In [19]:
result["Department"] = result["Department"].fillna("Not Assigned")

result["Department"]

result

   Emp_ID   Name  Dept_ID    Department
0     101  Rohit        1            HR
1     102   Amit        2            IT
2     103  Priya        3       Finance
3     104  Sneha        4  Not Assigned

In [20]:
#Q15: Combine everything: merge Sales, Products, and Customers tables into one clean report and export it to a new CSV.


# Sales DataFrame
sales = pd.DataFrame({
    'Sale_ID': [1001, 1002, 1003, 1004],
    'Customer_ID': [1, 2, 3, 1],
    'Product_ID': [101, 102, 103, 104],
    'Quantity': [2, 1, 3, 2]
})

# Products DataFrame
products = pd.DataFrame({
    'Product_ID': [101, 102, 103, 104],
    'Product_Name': ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
    'Price': [50000, 800, 1500, 12000]
})

# Customers DataFrame
customers = pd.DataFrame({
    'Customer_ID': [1, 2, 3],
    'Customer_Name': ['Rohit', 'Amit', 'Priya'],
    'City': ['Pune', 'Mumbai', 'Nagpur']
})


report = pd.merge(sales,products,on="Product_ID",how="left")

report = pd.merge(report,customers,on="Customer_ID",how="left")

report

,Sale_ID,Customer_ID,Product_ID,Quantity,Product_Name,Price,Customer_Name,City
0,1001,1,101,2,Laptop,50000,Rohit,Pune
1,1002,2,102,1,Mouse,800,Amit,Mumbai
2,1003,3,103,3,Keyboard,1500,Priya,Nagpur
3,1004,1,104,2,Monitor,12000,Rohit,Pune

In [21]:
report["Total_Amount"] = report["Quantity"] * report["Price"]

In [22]:
report

,Sale_ID,Customer_ID,Product_ID,Quantity,Product_Name,Price,Customer_Name,City,Total_Amount
0,1001,1,101,2,Laptop,50000,Rohit,Pune,100000
1,1002,2,102,1,Mouse,800,Amit,Mumbai,800
2,1003,3,103,3,Keyboard,1500,Priya,Nagpur,4500
3,1004,1,104,2,Monitor,12000,Rohit,Pune,24000

In [23]:
report = report[['Sale_ID', 'Customer_Name', 'City',
                 'Product_Name', 'Quantity', 'Price', 'Total_Amount']]

In [24]:
report

   Sale_ID Customer_Name    City Product_Name  Quantity  Price  Total_Amount
0     1001         Rohit    Pune       Laptop         2  50000        100000
1     1002          Amit  Mumbai        Mouse         1    800           800
2     1003         Priya  Nagpur     Keyboard         3   1500          4500
3     1004         Rohit    Pune      Monitor         2  12000         24000

In [25]:
report.to_csv("Sales_Report.csv",index=False)

print("CSV file Sales_Report.csv has been created successfully.")

CSV file Sales_Report.csv has been created successfully.