In [1]:
import numpy as np


import pandas as pd

In [2]:

data = pd.read_csv(r"C:\Users\Dell\OneDrive\Desktop\Data Analyst 2.0\Python Projects\Day 11\ecommerce_data_500_rows_Task_Data.csv")

In [3]:
data

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,TotalAmount,OrderDate,City,PaymentMethod,OrderStatus
0,ORD00001,CUST1001,Customer 1,Headphones,Fashion,2,637,1274,2025-01-02,Mumbai,Credit Card,Shipped
1,ORD00002,CUST1002,Customer 2,T-Shirt,Home,3,774,2322,2025-01-03,Delhi,Debit Card,Processing
2,ORD00003,CUST1003,Customer 3,Shoes,Books,4,911,3644,2025-01-04,Bengaluru,Cash on Delivery,Cancelled
3,ORD00004,CUST1004,Customer 4,Mixer,Sports,5,1048,5240,2025-01-05,Hyderabad,Net Banking,Delivered
4,ORD00005,CUST1005,Customer 5,Novel,Beauty,1,1185,1185,2025-01-06,Chennai,UPI,Shipped
...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD00496,CUST1496,Customer 496,Cricket Bat,Sports,2,952,1904,2025-05-12,Pune,Credit Card,Delivered
496,ORD00497,CUST1497,Customer 497,Face Wash,Beauty,3,1089,3267,2025-05-13,Mumbai,Debit Card,Shipped
497,ORD00498,CUST1498,Customer 498,Smartphone,Electronics,4,1226,4904,2025-05-14,Delhi,Cash on Delivery,Processing
498,ORD00499,CUST1499,Customer 499,Watch,Fashion,5,1363,6815,2025-05-15,Bengaluru,Net Banking,Cancelled
499,ORD00500,CUST1500,Customer 500,Laptop,Home,1,1500,1500,2025-05-16,Hyderabad,UPI,Delivered

In [7]:
data.head()

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,TotalAmount,OrderDate,City,PaymentMethod,OrderStatus
0,ORD00001,CUST1001,Customer 1,Headphones,Fashion,2,637,1274,2025-01-02,Mumbai,Credit Card,Shipped
1,ORD00002,CUST1002,Customer 2,T-Shirt,Home,3,774,2322,2025-01-03,Delhi,Debit Card,Processing
2,ORD00003,CUST1003,Customer 3,Shoes,Books,4,911,3644,2025-01-04,Bengaluru,Cash on Delivery,Cancelled
3,ORD00004,CUST1004,Customer 4,Mixer,Sports,5,1048,5240,2025-01-05,Hyderabad,Net Banking,Delivered
4,ORD00005,CUST1005,Customer 5,Novel,Beauty,1,1185,1185,2025-01-06,Chennai,UPI,Shipped

In [8]:
data.tail()

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,TotalAmount,OrderDate,City,PaymentMethod,OrderStatus
495,ORD00496,CUST1496,Customer 496,Cricket Bat,Sports,2,952,1904,2025-05-12,Pune,Credit Card,Delivered
496,ORD00497,CUST1497,Customer 497,Face Wash,Beauty,3,1089,3267,2025-05-13,Mumbai,Debit Card,Shipped
497,ORD00498,CUST1498,Customer 498,Smartphone,Electronics,4,1226,4904,2025-05-14,Delhi,Cash on Delivery,Processing
498,ORD00499,CUST1499,Customer 499,Watch,Fashion,5,1363,6815,2025-05-15,Bengaluru,Net Banking,Cancelled
499,ORD00500,CUST1500,Customer 500,Laptop,Home,1,1500,1500,2025-05-16,Hyderabad,UPI,Delivered

In [10]:
data.shape

(500, 12)

In [11]:
data.columns

Index(['OrderID', 'CustomerID', 'CustomerName', 'Product', 'Category',
       'Quantity', 'Price', 'TotalAmount', 'OrderDate', 'City',
       'PaymentMethod', 'OrderStatus'],
      dtype='object')

In [16]:
data.dtypes

OrderID          object
CustomerID       object
CustomerName     object
Product          object
Category         object
Quantity          int64
Price             int64
TotalAmount       int64
OrderDate        object
City             object
PaymentMethod    object
OrderStatus      object
dtype: object

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        500 non-null    object
 1   CustomerID     500 non-null    object
 2   CustomerName   500 non-null    object
 3   Product        500 non-null    object
 4   Category       500 non-null    object
 5   Quantity       500 non-null    int64
 6   Price          500 non-null    int64
 7   TotalAmount    500 non-null    int64
 8   OrderDate      500 non-null    object
 9   City           500 non-null    object
 10  PaymentMethod  500 non-null    object
 11  OrderStatus    500 non-null    object
dtypes: int64(3), object(9)
memory usage: 47.0+ KB

In [18]:
data.describe()

        Quantity        Price   TotalAmount
count  500.00000   500.000000    500.000000
mean     3.00000  2724.500000   8182.500000
std      1.41563  1306.943554   5803.488123
min      1.00000   510.000000    510.000000
25%      2.00000  1582.250000   3507.500000
50%      3.00000  2712.500000   6759.500000
75%      4.00000  3853.500000  11914.000000
max      5.00000  4999.000000  24890.000000

In [25]:
data[["CustomerName","Product","City"]]

     CustomerName      Product       City
0      Customer 1   Headphones     Mumbai
1      Customer 2      T-Shirt      Delhi
2      Customer 3        Shoes  Bengaluru
3      Customer 4        Mixer  Hyderabad
4      Customer 5        Novel    Chennai
..            ...          ...        ...
495  Customer 496  Cricket Bat       Pune
496  Customer 497    Face Wash     Mumbai
497  Customer 498   Smartphone      Delhi
498  Customer 499        Watch  Bengaluru
499  Customer 500       Laptop  Hyderabad

[500 rows x 3 columns]

In [27]:
data = data[data["City"] == "Mumbai"]

data

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,TotalAmount,OrderDate,City,PaymentMethod,OrderStatus
0,ORD00001,CUST1001,Customer 1,Headphones,Fashion,2,637,1274,2025-01-02,Mumbai,Credit Card,Shipped
8,ORD00009,CUST1009,Customer 9,Watch,Books,5,1733,8665,2025-01-10,Mumbai,Net Banking,Shipped
16,ORD00017,CUST1017,Customer 17,Face Wash,Beauty,3,2829,8487,2025-01-18,Mumbai,Debit Card,Shipped
24,ORD00025,CUST1025,Customer 25,Novel,Fashion,1,3925,3925,2025-01-26,Mumbai,UPI,Shipped
32,ORD00033,CUST1033,Customer 33,Shoes,Books,4,521,2084,2025-02-03,Mumbai,Cash on Delivery,Shipped
...,...,...,...,...,...,...,...,...,...,...,...,...
464,ORD00465,CUST1465,Customer 465,Novel,Books,1,1205,1205,2025-04-11,Mumbai,UPI,Shipped
472,ORD00473,CUST1473,Customer 473,Shoes,Beauty,4,2301,9204,2025-04-19,Mumbai,Cash on Delivery,Shipped
480,ORD00481,CUST1481,Customer 481,Headphones,Fashion,2,3397,6794,2025-04-27,Mumbai,Credit Card,Shipped
488,ORD00489,CUST1489,Customer 489,Watch,Books,5,4493,22465,2025-05-05,Mumbai,Net Banking,Shipped
496,ORD00497,CUST1497,Customer 497,Face Wash,Beauty,3,1089,3267,2025-05-13,Mumbai,Debit Card,Shipped

In [36]:
data2 = data[(data["PaymentMethod"] == "UPI") & (data["Category"] == "Fashion")]

data2

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,TotalAmount,OrderDate,City,PaymentMethod,OrderStatus
264,ORD00265,CUST1265,Customer 265,Novel,Fashion,1,805,805,2025-09-23,Mumbai,UPI,Shipped
144,ORD00145,CUST1145,Customer 145,Novel,Fashion,1,2365,2365,2025-05-26,Mumbai,UPI,Shipped
384,ORD00385,CUST1385,Customer 385,Novel,Fashion,1,3745,3745,2025-01-21,Mumbai,UPI,Shipped
24,ORD00025,CUST1025,Customer 25,Novel,Fashion,1,3925,3925,2025-01-26,Mumbai,UPI,Shipped

In [37]:
data = data.sort_values(by="TotalAmount")

data

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,TotalAmount,OrderDate,City,PaymentMethod,OrderStatus
264,ORD00265,CUST1265,Customer 265,Novel,Fashion,1,805,805,2025-09-23,Mumbai,UPI,Shipped
144,ORD00145,CUST1145,Customer 145,Novel,Fashion,1,2365,2365,2025-05-26,Mumbai,UPI,Shipped
384,ORD00385,CUST1385,Customer 385,Novel,Fashion,1,3745,3745,2025-01-21,Mumbai,UPI,Shipped
24,ORD00025,CUST1025,Customer 25,Novel,Fashion,1,3925,3925,2025-01-26,Mumbai,UPI,Shipped