In [3]:
#Q1: Import pandas and create a Series from a Python list with custom index labels.

import numpy as np
import pandas as pd

marks = [80,86,96,89,78,90]

series = pd.Series(marks,index =["A","B","C","D","E","F"])

series

A    80
B    86
C    96
D    89
E    78
F    90
dtype: int64

In [6]:
#Q2: Create a DataFrame from a dictionary containing columns: Name, Age, City, Salary (5 rows).

data = {
    "Name":("Vaishnavi","Rohit","Ganesh","Siddhesh","Aditya"),
    "Age" :(22,23,21,22,23),
    "City" : ("Pune","Pune","Jalna","Pune","Daund"),
    "Salary" : (88000,80000,76000,79000,80500)

}

data = pd.DataFrame(data)

data

        Name  Age   City  Salary
0  Vaishnavi   22   Pune   88000
1      Rohit   23   Pune   80000
2     Ganesh   21  Jalna   76000
3   Siddhesh   22   Pune   79000
4     Aditya   23  Daund   80500

In [8]:
#Q3: Load a CSV file into a DataFrame using pd.read_csv() and display the first 5 and last 5 rows.

data = pd.read_csv(r"C:\Users\Dell\OneDrive\Desktop\Data Analyst 2.0\Python Projects\Day 11\employees_100.csv")

In [9]:
data

   EmployeeID          Name Department  Age  Salary        City
0        E001    Employee 1         HR   23   30500        Pune
1        E002    Employee 2         IT   24   31000      Mumbai
2        E003    Employee 3    Finance   25   31500      Nashik
3        E004    Employee 4      Sales   26   32000      Nagpur
4        E005    Employee 5  Marketing   27   32500  Aurangabad
..        ...           ...        ...  ...     ...         ...
95       E096   Employee 96         HR   23   78000        Pune
96       E097   Employee 97         IT   24   78500      Mumbai
97       E098   Employee 98    Finance   25   79000      Nashik
98       E099   Employee 99      Sales   26   79500      Nagpur
99       E100  Employee 100  Marketing   27   80000  Aurangabad

[100 rows x 6 columns]

In [11]:
(data.head())

  EmployeeID        Name Department  Age  Salary        City
0       E001  Employee 1         HR   23   30500        Pune
1       E002  Employee 2         IT   24   31000      Mumbai
2       E003  Employee 3    Finance   25   31500      Nashik
3       E004  Employee 4      Sales   26   32000      Nagpur
4       E005  Employee 5  Marketing   27   32500  Aurangabad

In [12]:
data.tail()

   EmployeeID          Name Department  Age  Salary        City
95       E096   Employee 96         HR   23   78000        Pune
96       E097   Employee 97         IT   24   78500      Mumbai
97       E098   Employee 98    Finance   25   79000      Nashik
98       E099   Employee 99      Sales   26   79500      Nagpur
99       E100  Employee 100  Marketing   27   80000  Aurangabad

In [14]:
#Q4: Display the shape, columns, dtypes, and summary statistics (describe()) of a DataFrame.

data.shape

(100, 6)

In [15]:
data.columns

Index(['EmployeeID', 'Name', 'Department', 'Age', 'Salary', 'City'], dtype='object')

In [17]:
data.dtypes

EmployeeID    object
Name          object
Department    object
Age            int64
Salary         int64
City          object
dtype: object

In [18]:
data.describe()

              Age        Salary
count  100.000000    100.000000
mean    30.700000  55250.000000
std      5.533187  14505.745988
min     22.000000  30500.000000
25%     26.000000  42875.000000
50%     30.500000  55250.000000
75%     35.250000  67625.000000
max     40.000000  80000.000000

In [20]:
#Q5: Select a single column and multiple columns from a DataFrame.

data["Name"]

0       Employee 1
1       Employee 2
2       Employee 3
3       Employee 4
4       Employee 5
          ...
95     Employee 96
96     Employee 97
97     Employee 98
98     Employee 99
99    Employee 100
Name: Name, Length: 100, dtype: object

In [22]:
data[["Name","Age","Salary"]]

            Name  Age  Salary
0     Employee 1   23   30500
1     Employee 2   24   31000
2     Employee 3   25   31500
3     Employee 4   26   32000
4     Employee 5   27   32500
..           ...  ...     ...
95   Employee 96   23   78000
96   Employee 97   24   78500
97   Employee 98   25   79000
98   Employee 99   26   79500
99  Employee 100   27   80000

[100 rows x 3 columns]

In [24]:
#Q6: Select rows using loc[] (label-based) and iloc[] (position-based) indexing.

data.head()

  EmployeeID        Name Department  Age  Salary        City
0       E001  Employee 1         HR   23   30500        Pune
1       E002  Employee 2         IT   24   31000      Mumbai
2       E003  Employee 3    Finance   25   31500      Nashik
3       E004  Employee 4      Sales   26   32000      Nagpur
4       E005  Employee 5  Marketing   27   32500  Aurangabad

In [28]:
data.loc[0:5]

  EmployeeID        Name Department  Age  Salary        City
0       E001  Employee 1         HR   23   30500        Pune
1       E002  Employee 2         IT   24   31000      Mumbai
2       E003  Employee 3    Finance   25   31500      Nashik
3       E004  Employee 4      Sales   26   32000      Nagpur
4       E005  Employee 5  Marketing   27   32500  Aurangabad
5       E006  Employee 6         HR   28   33000        Pune

In [29]:
data.loc[2:8,["Name","Age","Department"]]

         Name  Age Department
2  Employee 3   25    Finance
3  Employee 4   26      Sales
4  Employee 5   27  Marketing
5  Employee 6   28         HR
6  Employee 7   29         IT
7  Employee 8   30    Finance
8  Employee 9   31      Sales

In [30]:
data.iloc[0:5]

  EmployeeID        Name Department  Age  Salary        City
0       E001  Employee 1         HR   23   30500        Pune
1       E002  Employee 2         IT   24   31000      Mumbai
2       E003  Employee 3    Finance   25   31500      Nashik
3       E004  Employee 4      Sales   26   32000      Nagpur
4       E005  Employee 5  Marketing   27   32500  Aurangabad

In [31]:
data.iloc[0:6,1:5]

         Name Department  Age  Salary
0  Employee 1         HR   23   30500
1  Employee 2         IT   24   31000
2  Employee 3    Finance   25   31500
3  Employee 4      Sales   26   32000
4  Employee 5  Marketing   27   32500
5  Employee 6         HR   28   33000

In [36]:
#Q7: Add a new calculated column to a DataFrame (e.g., Bonus = 10% of Salary).

data["Bonus"] = data["Salary"] * 0.10

data.columns

data.head()

  EmployeeID        Name Department  Age  Salary        City   Bonus
0       E001  Employee 1         HR   23   30500        Pune  3050.0
1       E002  Employee 2         IT   24   31000      Mumbai  3100.0
2       E003  Employee 3    Finance   25   31500      Nashik  3150.0
3       E004  Employee 4      Sales   26   32000      Nagpur  3200.0
4       E005  Employee 5  Marketing   27   32500  Aurangabad  3250.0

In [40]:
#Q8: Rename one or more column names in a DataFrame using rename().

data.rename(columns = {"Salary" : "Monthly Salary"},inplace=True)

data

,EmployeeID,Name,Department,Age,Monthly Salary,City,Bonus
0,E001,Employee 1,HR,23,30500,Pune,3050.0
1,E002,Employee 2,IT,24,31000,Mumbai,3100.0
2,E003,Employee 3,Finance,25,31500,Nashik,3150.0
3,E004,Employee 4,Sales,26,32000,Nagpur,3200.0
4,E005,Employee 5,Marketing,27,32500,Aurangabad,3250.0
...,...,...,...,...,...,...,...
95,E096,Employee 96,HR,23,78000,Pune,7800.0
96,E097,Employee 97,IT,24,78500,Mumbai,7850.0
97,E098,Employee 98,Finance,25,79000,Nashik,7900.0
98,E099,Employee 99,Sales,26,79500,Nagpur,7950.0
99,E100,Employee 100,Marketing,27,80000,Aurangabad,8000.0

In [42]:
data.rename(columns={
    "Name" : "Emp_Name",
    "Age" : "Emp_Age"
},inplace=True)

In [43]:
data

,EmployeeID,Emp_Name,Department,Emp_Age,Monthly Salary,City,Bonus
0,E001,Employee 1,HR,23,30500,Pune,3050.0
1,E002,Employee 2,IT,24,31000,Mumbai,3100.0
2,E003,Employee 3,Finance,25,31500,Nashik,3150.0
3,E004,Employee 4,Sales,26,32000,Nagpur,3200.0
4,E005,Employee 5,Marketing,27,32500,Aurangabad,3250.0
...,...,...,...,...,...,...,...
95,E096,Employee 96,HR,23,78000,Pune,7800.0
96,E097,Employee 97,IT,24,78500,Mumbai,7850.0
97,E098,Employee 98,Finance,25,79000,Nashik,7900.0
98,E099,Employee 99,Sales,26,79500,Nagpur,7950.0
99,E100,Employee 100,Marketing,27,80000,Aurangabad,8000.0

In [45]:
#Q9: Sort a DataFrame by a single column and by multiple columns.

data.sort_values(by="Monthly Salary")

,EmployeeID,Emp_Name,Department,Emp_Age,Monthly Salary,City,Bonus
0,E001,Employee 1,HR,23,30500,Pune,3050.0
1,E002,Employee 2,IT,24,31000,Mumbai,3100.0
2,E003,Employee 3,Finance,25,31500,Nashik,3150.0
3,E004,Employee 4,Sales,26,32000,Nagpur,3200.0
4,E005,Employee 5,Marketing,27,32500,Aurangabad,3250.0
...,...,...,...,...,...,...,...
95,E096,Employee 96,HR,23,78000,Pune,7800.0
96,E097,Employee 97,IT,24,78500,Mumbai,7850.0
97,E098,Employee 98,Finance,25,79000,Nashik,7900.0
98,E099,Employee 99,Sales,26,79500,Nagpur,7950.0
99,E100,Employee 100,Marketing,27,80000,Aurangabad,8000.0

In [50]:
data.sort_values(by=["Monthly Salary","Emp_Age","Bonus"])

,EmployeeID,Emp_Name,Department,Emp_Age,Monthly Salary,City,Bonus
0,E001,Employee 1,HR,23,30500,Pune,3050.0
1,E002,Employee 2,IT,24,31000,Mumbai,3100.0
2,E003,Employee 3,Finance,25,31500,Nashik,3150.0
3,E004,Employee 4,Sales,26,32000,Nagpur,3200.0
4,E005,Employee 5,Marketing,27,32500,Aurangabad,3250.0
...,...,...,...,...,...,...,...
95,E096,Employee 96,HR,23,78000,Pune,7800.0
96,E097,Employee 97,IT,24,78500,Mumbai,7850.0
97,E098,Employee 98,Finance,25,79000,Nashik,7900.0
98,E099,Employee 99,Sales,26,79500,Nagpur,7950.0
99,E100,Employee 100,Marketing,27,80000,Aurangabad,8000.0

In [51]:
#Q10: Use info() to check data types and non-null counts of every column.

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EmployeeID      100 non-null    object
 1   Emp_Name        100 non-null    object
 2   Department      100 non-null    object
 3   Emp_Age         100 non-null    int64
 4   Monthly Salary  100 non-null    int64
 5   City            100 non-null    object
 6   Bonus           100 non-null    float64
dtypes: float64(1), int64(2), object(4)
memory usage: 5.6+ KB

In [57]:
#Q11: Filter rows in a DataFrame where a column value meets a condition (e.g., Age > 25)

data = data[data["Emp_Age"] > 25]

data

,EmployeeID,Emp_Name,Department,Emp_Age,Monthly Salary,City,Bonus
3,E004,Employee 4,Sales,26,32000,Nagpur,3200.0
4,E005,Employee 5,Marketing,27,32500,Aurangabad,3250.0
5,E006,Employee 6,HR,28,33000,Pune,3300.0
6,E007,Employee 7,IT,29,33500,Mumbai,3350.0
7,E008,Employee 8,Finance,30,34000,Nashik,3400.0
...,...,...,...,...,...,...,...
91,E092,Employee 92,IT,38,76000,Mumbai,7600.0
92,E093,Employee 93,Finance,39,76500,Nashik,7650.0
93,E094,Employee 94,Sales,40,77000,Nagpur,7700.0
98,E099,Employee 99,Sales,26,79500,Nagpur,7950.0
99,E100,Employee 100,Marketing,27,80000,Aurangabad,8000.0

In [76]:
#Q12: Filter rows using multiple conditions combined with AND (&) and OR (|).



print(data[(data["Emp_Age"] > 25) & (data["Monthly Salary"] > 35000)])

   EmployeeID      Emp_Name Department  Emp_Age  Monthly Salary        City  \
10       E011   Employee 11         HR       33           35500        Pune
11       E012   Employee 12         IT       34           36000      Mumbai
12       E013   Employee 13    Finance       35           36500      Nashik
13       E014   Employee 14      Sales       36           37000      Nagpur
14       E015   Employee 15  Marketing       37           37500  Aurangabad
..        ...           ...        ...      ...             ...         ...
91       E092   Employee 92         IT       38           76000      Mumbai
92       E093   Employee 93    Finance       39           76500      Nashik
93       E094   Employee 94      Sales       40           77000      Nagpur
98       E099   Employee 99      Sales       26           79500      Nagpur
99       E100  Employee 100  Marketing       27           80000  Aurangabad

     Bonus
10  3550.0
11  3600.0
12  3650.0
13  3700.0
14  3750.0
..     ...
91  7600.0
92  7650.0
93  7700.0
98  7950.0
99  8000.0

[70 rows x 7 columns]

In [78]:
print(data[(data["Department"] == "IT") | (data["City"] == "Pune")])

   EmployeeID     Emp_Name Department  Emp_Age  Monthly Salary    City   Bonus
5        E006   Employee 6         HR       28           33000    Pune  3300.0
6        E007   Employee 7         IT       29           33500  Mumbai  3350.0
10       E011  Employee 11         HR       33           35500    Pune  3550.0
11       E012  Employee 12         IT       34           36000  Mumbai  3600.0
15       E016  Employee 16         HR       38           38000    Pune  3800.0
16       E017  Employee 17         IT       39           38500  Mumbai  3850.0
25       E026  Employee 26         HR       29           43000    Pune  4300.0
26       E027  Employee 27         IT       30           43500  Mumbai  4350.0
30       E031  Employee 31         HR       34           45500    Pune  4550.0
31       E032  Employee 32         IT       35           46000  Mumbai  4600.0
35       E036  Employee 36         HR       39           48000    Pune  4800.0
36       E037  Employee 37         IT       40           48500  Mumbai  4850.0
41       E042  Employee 42         IT       26           51000  Mumbai  5100.0
45       E046  Employee 46         HR       30           53000    Pune  5300.0
46       E047  Employee 47         IT       31           53500  Mumbai  5350.0
50       E051  Employee 51         HR       35           55500    Pune  5550.0
51       E052  Employee 52         IT       36           56000  Mumbai  5600.0
55       E056  Employee 56         HR       40           58000    Pune  5800.0
60       E061  Employee 61         HR       26           60500    Pune  6050.0
61       E062  Employee 62         IT       27           61000  Mumbai  6100.0
65       E066  Employee 66         HR       31           63000    Pune  6300.0
66       E067  Employee 67         IT       32           63500  Mumbai  6350.0
70       E071  Employee 71         HR       36           65500    Pune  6550.0
71       E072  Employee 72         IT       37           66000  Mumbai  6600.0
80       E081  Employee 81         HR       27           70500    Pune  7050.0
81       E082  Employee 82         IT       28           71000  Mumbai  7100.0
85       E086  Employee 86         HR       32           73000    Pune  7300.0
86       E087  Employee 87         IT       33           73500  Mumbai  7350.0
90       E091  Employee 91         HR       37           75500    Pune  7550.0
91       E092  Employee 92         IT       38           76000  Mumbai  7600.0

In [ ]:
#Q13: Drop a column and drop a row from a DataFrame using drop(). 

data = data.drop("Bonus",axis = 1)

KeyError: "['Bonus'] not found in axis"

In [81]:
data

   EmployeeID      Emp_Name Department  Emp_Age  Monthly Salary        City
3        E004    Employee 4      Sales       26           32000      Nagpur
4        E005    Employee 5  Marketing       27           32500  Aurangabad
5        E006    Employee 6         HR       28           33000        Pune
6        E007    Employee 7         IT       29           33500      Mumbai
7        E008    Employee 8    Finance       30           34000      Nashik
..        ...           ...        ...      ...             ...         ...
91       E092   Employee 92         IT       38           76000      Mumbai
92       E093   Employee 93    Finance       39           76500      Nashik
93       E094   Employee 94      Sales       40           77000      Nagpur
98       E099   Employee 99      Sales       26           79500      Nagpur
99       E100  Employee 100  Marketing       27           80000  Aurangabad

[77 rows x 6 columns]

In [83]:
data = data.drop(3)

In [84]:
data

   EmployeeID      Emp_Name Department  Emp_Age  Monthly Salary        City
4        E005    Employee 5  Marketing       27           32500  Aurangabad
5        E006    Employee 6         HR       28           33000        Pune
6        E007    Employee 7         IT       29           33500      Mumbai
7        E008    Employee 8    Finance       30           34000      Nashik
8        E009    Employee 9      Sales       31           34500      Nagpur
..        ...           ...        ...      ...             ...         ...
91       E092   Employee 92         IT       38           76000      Mumbai
92       E093   Employee 93    Finance       39           76500      Nashik
93       E094   Employee 94      Sales       40           77000      Nagpur
98       E099   Employee 99      Sales       26           79500      Nagpur
99       E100  Employee 100  Marketing       27           80000  Aurangabad

[76 rows x 6 columns]

In [85]:
#Q14: Reset the index of a DataFrame after filtering, using reset_index().\

data.reset_index()

,index,EmployeeID,Emp_Name,Department,Emp_Age,Monthly Salary,City
0,4,E005,Employee 5,Marketing,27,32500,Aurangabad
1,5,E006,Employee 6,HR,28,33000,Pune
2,6,E007,Employee 7,IT,29,33500,Mumbai
3,7,E008,Employee 8,Finance,30,34000,Nashik
4,8,E009,Employee 9,Sales,31,34500,Nagpur
...,...,...,...,...,...,...,...
71,91,E092,Employee 92,IT,38,76000,Mumbai
72,92,E093,Employee 93,Finance,39,76500,Nashik
73,93,E094,Employee 94,Sales,40,77000,Nagpur
74,98,E099,Employee 99,Sales,26,79500,Nagpur
75,99,E100,Employee 100,Marketing,27,80000,Aurangabad

In [95]:
#Q15: Convert a DataFrame column to a NumPy array and to a Python list.

salary = data["Monthly Salary"].to_numpy()

salary2 = data["Monthly Salary"].to_list()

In [94]:
salary

array([32500, 33000, 33500, 34000, 34500, 35000, 35500, 36000, 36500,
       37000, 37500, 38000, 38500, 39000, 41500, 42000, 42500, 43000,
       43500, 44000, 44500, 45000, 45500, 46000, 46500, 47000, 47500,
       48000, 48500, 51000, 51500, 52000, 52500, 53000, 53500, 54000,
       54500, 55000, 55500, 56000, 56500, 57000, 57500, 58000, 60500,
       61000, 61500, 62000, 62500, 63000, 63500, 64000, 64500, 65000,
       65500, 66000, 66500, 67000, 67500, 70000, 70500, 71000, 71500,
       72000, 72500, 73000, 73500, 74000, 74500, 75000, 75500, 76000,
       76500, 77000, 79500, 80000])

In [ ]:


type(salary)

numpy.ndarray

In [96]:
salary2

[32500,
 33000,
 33500,
 34000,
 34500,
 35000,
 35500,
 36000,
 36500,
 37000,
 37500,
 38000,
 38500,
 39000,
 41500,
 42000,
 42500,
 43000,
 43500,
 44000,
 44500,
 45000,
 45500,
 46000,
 46500,
 47000,
 47500,
 48000,
 48500,
 51000,
 51500,
 52000,
 52500,
 53000,
 53500,
 54000,
 54500,
 55000,
 55500,
 56000,
 56500,
 57000,
 57500,
 58000,
 60500,
 61000,
 61500,
 62000,
 62500,
 63000,
 63500,
 64000,
 64500,
 65000,
 65500,
 66000,
 66500,
 67000,
 67500,
 70000,
 70500,
 71000,
 71500,
 72000,
 72500,
 73000,
 73500,
 74000,
 74500,
 75000,
 75500,
 76000,
 76500,
 77000,
 79500,
 80000]

In [97]:
type(salary2)

list